import { Inter } from "next/font/google";

// If loading a variable font, you don't need to specify the font weight
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
    title: "Jour x Brilink",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>{children}</body>
        </html>
    );
}
